version: '3.9'

services:

  app:
    image: cestxvcdim/skypro_coursework5:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    command: flask run
    restart: always

  nginx:
    image: nginx:1.19.3
    ports:
      - 80:5000
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
